version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: aiaas-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: aiaas
      POSTGRES_PASSWORD: aiaas_dev_password
      POSTGRES_DB: aiaas
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: aiaas-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  mock-ml:
    build: ./mock-ml-services
    container_name: aiaas-mock-ml
    restart: unless-stopped
    ports:
      - "9000:9000"

  backend:
    build: ./backend
    container_name: aiaas-backend
    environment:
      DATABASE_URL: postgresql+asyncpg://aiaas:aiaas_dev_password@postgres:5432/aiaas
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
      - mock-ml
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: aiaas-frontend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  postgres_data: