"""add requests table

Revision ID: f7e31b97a767
Revises: 4c8d279daa76
Create Date: 2026-09-22 21:46:18.946343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e31b97a767'
down_revision: Union[str, None] = '4c8d279daa76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('api_key_id', sa.Uuid(), nullable=False),
    sa.Column('service', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_created_at'), 'requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_requests_org_id'), 'requests', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requests_org_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_created_at'), table_name='requests')
    op.drop_table('requests')
    # ### end Alembic commands ###
